# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  create:
    branches: [ "release/**" ]
  push:
    branches: [ "main" ]
    tags:
      - v*
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
  
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Atypical.VirtualFileSystem.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
        include-prerelease: false
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore
    
    - name: Run Test
      run: dotnet test --configuration $BUILD_CONFIG --no-build --verbosity normal --framework net7.0
      
    - name: Publish to NuGet
      if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: ${{ !contains(github.ref, 'beta') }}
      with:
        draft: false
        name: ${{ github.ref_name }} Release
        body_path: Src/Library/changelog.md
